import Head from "next/head";
import Link from "next/link";
import styles from "./index.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link className={styles["start-game-btn"]} href={`/game`}>
          <p>Start Game</p>
        </Link>
      </main>
    </>
  );
}
